ALTER USER postgres WITH PASSWORD '123';

CREATE DATABASE game4;
CREATE USER "Gameuser" WITH ENCRYPTED PASSWORD '123';
ALTER ROLE "Gameuser" WITH LOGIN;
CREATE USER "Webuser" WITH ENCRYPTED PASSWORD '123';
ALTER ROLE "Webuser" WITH LOGIN;

CREATE DATABASE game4;