ALTER USER postgres WITH PASSWORD '123';

CREATE USER "Gameuser" WITH ENCRYPTED PASSWORD '123';
ALTER ROLE "Gameuser" WITH LOGIN;
CREATE USER "Webuser" WITH ENCRYPTED PASSWORD '123';
ALTER ROLE "Webuser" WITH LOGIN;

CREATE DATABASE game4;
GRANT SELECT ON ALL TABLES IN SCHEMA "gameTables" TO "Gameuser";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA "gameTables" TO "Webuser";
